export const products = [
  {
    id: 1,
    title: "backpack",
    price: "100$",
    rating: 4,
    img: "/images/backpack-1.jpg",
    capture: ["/images/backpack-2.jpg", "/images/backpack-3.jpg"],
    reviews: 50,
    desc: "Durable and spacious backpack perfect for traveling and daily use.",
  },
  {
    id: 2,
    title: "headphones",
    price: "150$",
    rating: 4,
    img: "/images/headphones-2.jpg",
    capture: ["/images/headphones-1.jpg"],
    reviews: 120,
    desc: "Wireless noise-cancelling headphones with crystal clear sound and long battery life.",
  },
  {
    id: 3,
    title: "porridge",
    price: "5$",
    rating: 4,
    img: "/images/porridge-1.jpg",
    capture: ["/images/porridge-2.jpg"],
    reviews: 35,
    desc: "Healthy and nutritious instant porridge for a quick and satisfying breakfast.",
  },
  {
    id: 4,
    title: "PS 5",
    price: "500$",
    rating: 5,
    img: "/images/ps5-1.jpg",
    capture: ["/images/ps5-2.jpg", "/images/ps5-3.jpg"],
    reviews: 200,
    desc: "Next-generation gaming console with stunning graphics and fast loading times.",
  },
  {
    id: 5,
    title: "Redmi",
    price: "250$",
    rating: 4,
    img: "/images/redmi-1.jpg",
    capture: ["/images/redmi-2.jpg"],
    reviews: 80,
    desc: "Affordable smartphone with impressive features and a long-lasting battery.",
  },
  {
    id: 6,
    title: "Samsung S24",
    price: "999$",
    rating: 5,
    img: "/images/samsung-s24-1.jpg",
    capture: ["/images/samsung-s24-2.jpg"],
    reviews: 150,
    desc: "High-end smartphone with an exceptional camera and advanced display technology.",
  },
  {
    id: 7,
    title: "Artel TV",
    price: "300$",
    rating: 4,
    img: "/images/artel-tv-1.jpg",
    capture: ["/images/artel-tv-2.jpg"],
    reviews: 60,
    desc: "Smart TV with a sleek design and vivid display for an immersive viewing experience.",
  },
  {
    id: 8,
    title: "Boss watches",
    price: "200$",
    rating: 4,
    img: "/images/boss-watches-1.jpg",
    capture: ["/images/boss-watches-2.jpg"],
    reviews: 90,
    desc: "Elegant and stylish watches that combine functionality and fashion.",
  },
  {
    id: 9,
    title: "Wet wipes",
    price: "3$",
    rating: 4,
    img: "/images/wet-wipes-1.jpg",
    capture: ["/images/wet-wipes-2.jpg"],
    reviews: 40,
    desc: "Soft and refreshing wet wipes for on-the-go cleaning and hygiene.",
  },
];
